/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as DashboardRouteImport } from './routes/dashboard/route'
import { Route as AuthRouteImport } from './routes/auth/route'
import { Route as IndexImport } from './routes/index'
import { Route as LayoutsMainImport } from './routes/layouts/main'
import { Route as AuthForgotPasswordImport } from './routes/auth/forgot-password'
import { Route as AuthChangePasswordImport } from './routes/auth/change-password'

// Create Virtual Routes

const AuthRegisterLazyImport = createFileRoute('/auth/register')()
const AuthLoginLazyImport = createFileRoute('/auth/login')()
const DashboardDeveloperIndexLazyImport = createFileRoute(
  '/dashboard/developer/',
)()
const DashboardDeveloperAddAssetIndexLazyImport = createFileRoute(
  '/dashboard/developer/add-asset/',
)()

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRouteRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const AuthRouteRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthRegisterLazyRoute = AuthRegisterLazyImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any).lazy(() => import('./routes/auth/register.lazy').then((d) => d.Route))

const AuthLoginLazyRoute = AuthLoginLazyImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any).lazy(() => import('./routes/auth/login.lazy').then((d) => d.Route))

const LayoutsMainRoute = LayoutsMainImport.update({
  id: '/layouts/main',
  path: '/layouts/main',
  getParentRoute: () => rootRoute,
} as any)

const AuthForgotPasswordRoute = AuthForgotPasswordImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthChangePasswordRoute = AuthChangePasswordImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => AuthRouteRoute,
} as any)

const DashboardDeveloperIndexLazyRoute =
  DashboardDeveloperIndexLazyImport.update({
    id: '/developer/',
    path: '/developer/',
    getParentRoute: () => DashboardRouteRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/developer/index.lazy').then((d) => d.Route),
  )

const DashboardDeveloperAddAssetIndexLazyRoute =
  DashboardDeveloperAddAssetIndexLazyImport.update({
    id: '/developer/add-asset/',
    path: '/developer/add-asset/',
    getParentRoute: () => DashboardRouteRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/developer/add-asset/index.lazy').then(
      (d) => d.Route,
    ),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/auth/change-password': {
      id: '/auth/change-password'
      path: '/change-password'
      fullPath: '/auth/change-password'
      preLoaderRoute: typeof AuthChangePasswordImport
      parentRoute: typeof AuthRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordImport
      parentRoute: typeof AuthRouteImport
    }
    '/layouts/main': {
      id: '/layouts/main'
      path: '/layouts/main'
      fullPath: '/layouts/main'
      preLoaderRoute: typeof LayoutsMainImport
      parentRoute: typeof rootRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginLazyImport
      parentRoute: typeof AuthRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterLazyImport
      parentRoute: typeof AuthRouteImport
    }
    '/dashboard/developer/': {
      id: '/dashboard/developer/'
      path: '/developer'
      fullPath: '/dashboard/developer'
      preLoaderRoute: typeof DashboardDeveloperIndexLazyImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/developer/add-asset/': {
      id: '/dashboard/developer/add-asset/'
      path: '/developer/add-asset'
      fullPath: '/dashboard/developer/add-asset'
      preLoaderRoute: typeof DashboardDeveloperAddAssetIndexLazyImport
      parentRoute: typeof DashboardRouteImport
    }
  }
}

// Create and export the route tree

interface AuthRouteRouteChildren {
  AuthChangePasswordRoute: typeof AuthChangePasswordRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginLazyRoute: typeof AuthLoginLazyRoute
  AuthRegisterLazyRoute: typeof AuthRegisterLazyRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthChangePasswordRoute: AuthChangePasswordRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginLazyRoute: AuthLoginLazyRoute,
  AuthRegisterLazyRoute: AuthRegisterLazyRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardDeveloperIndexLazyRoute: typeof DashboardDeveloperIndexLazyRoute
  DashboardDeveloperAddAssetIndexLazyRoute: typeof DashboardDeveloperAddAssetIndexLazyRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardDeveloperIndexLazyRoute: DashboardDeveloperIndexLazyRoute,
  DashboardDeveloperAddAssetIndexLazyRoute:
    DashboardDeveloperAddAssetIndexLazyRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth/change-password': typeof AuthChangePasswordRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/layouts/main': typeof LayoutsMainRoute
  '/auth/login': typeof AuthLoginLazyRoute
  '/auth/register': typeof AuthRegisterLazyRoute
  '/dashboard/developer': typeof DashboardDeveloperIndexLazyRoute
  '/dashboard/developer/add-asset': typeof DashboardDeveloperAddAssetIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth/change-password': typeof AuthChangePasswordRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/layouts/main': typeof LayoutsMainRoute
  '/auth/login': typeof AuthLoginLazyRoute
  '/auth/register': typeof AuthRegisterLazyRoute
  '/dashboard/developer': typeof DashboardDeveloperIndexLazyRoute
  '/dashboard/developer/add-asset': typeof DashboardDeveloperAddAssetIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth/change-password': typeof AuthChangePasswordRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/layouts/main': typeof LayoutsMainRoute
  '/auth/login': typeof AuthLoginLazyRoute
  '/auth/register': typeof AuthRegisterLazyRoute
  '/dashboard/developer/': typeof DashboardDeveloperIndexLazyRoute
  '/dashboard/developer/add-asset/': typeof DashboardDeveloperAddAssetIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/about'
    | '/auth/change-password'
    | '/auth/forgot-password'
    | '/layouts/main'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/developer'
    | '/dashboard/developer/add-asset'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/about'
    | '/auth/change-password'
    | '/auth/forgot-password'
    | '/layouts/main'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/developer'
    | '/dashboard/developer/add-asset'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/about'
    | '/auth/change-password'
    | '/auth/forgot-password'
    | '/layouts/main'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/developer/'
    | '/dashboard/developer/add-asset/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  LayoutsMainRoute: typeof LayoutsMainRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  LayoutsMainRoute: LayoutsMainRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/auth",
        "/dashboard",
        "/about",
        "/layouts/main"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/auth": {
      "filePath": "auth/route.tsx",
      "children": [
        "/auth/change-password",
        "/auth/forgot-password",
        "/auth/login",
        "/auth/register"
      ]
    },
    "/dashboard": {
      "filePath": "dashboard/route.tsx",
      "children": [
        "/dashboard/developer/",
        "/dashboard/developer/add-asset/"
      ]
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/auth/change-password": {
      "filePath": "auth/change-password.tsx",
      "parent": "/auth"
    },
    "/auth/forgot-password": {
      "filePath": "auth/forgot-password.tsx",
      "parent": "/auth"
    },
    "/layouts/main": {
      "filePath": "layouts/main.tsx"
    },
    "/auth/login": {
      "filePath": "auth/login.lazy.tsx",
      "parent": "/auth"
    },
    "/auth/register": {
      "filePath": "auth/register.lazy.tsx",
      "parent": "/auth"
    },
    "/dashboard/developer/": {
      "filePath": "dashboard/developer/index.lazy.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/developer/add-asset/": {
      "filePath": "dashboard/developer/add-asset/index.lazy.tsx",
      "parent": "/dashboard"
    }
  }
}
ROUTE_MANIFEST_END */
